name: Test Main Flow

on:
  workflow_dispatch: # 手動トリガー対応

  push:
    paths:
      - "src/tests/test_main.py"
      - "src/main.py"
      - ".github/workflows/test_main.yml"
  pull_request:
    paths:
      - "src/tests/test_main.py"
      - "src/main.py"
      - ".github/workflows/test_main.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LINE_CHANNEL_ACCESS_TOKEN1: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN1 }}
      LINE_CHANNEL_ACCESS_TOKEN2: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN2 }}
      LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Debug environment variables
        run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN1: $LINE_CHANNEL_ACCESS_TOKEN1"
          echo "LINE_CHANNEL_ACCESS_TOKEN2: $LINE_CHANNEL_ACCESS_TOKEN2"
          echo "LINE_GROUP_ID: $LINE_GROUP_ID"
          echo "GOOGLE_API_KEY: $GOOGLE_API_KEY"

      - name: Install src as a module
        run: pip install -e src

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main flow test
        run: python src/tests/test_main.py
