name: LINE Webhook Test

on:
  push:
    branches:
      - main  # メインブランチにプッシュ時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # GitHubのリポジトリを取得

      - name: Install dependencies
        run: pip install requests  # requests をインストール

      - name: Send test message to LINE
        env:
          LINE_CHANNEL_ACCESS_TOKEN2: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN2 }}  # GitHub Secrets の値を使用
        run: |
          python -c "
          import requests;
          headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + '${{ secrets.LINE_CHANNEL_ACCESS_TOKEN2 }}'};
          data = {'to': 'YOUR_GROUP_OR_USER_ID', 'messages': [{'type': 'text', 'text': 'GitHub Actions からのテストメッセージ'}]};
          response = requests.post('https://api.line.me/v2/bot/message/push', headers=headers, json=data);
          print(response.status_code, response.json())"
